
cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    credentials:
      access-key: dummy
      secret-key: dummy
    end-point:
      uri: http://localhost:4566
    queue:
      uri: http://localhost:4566
      name: sample-queue