
cloud:
  aws:
    stack:
      auto: false
    region:
      static: eu-west-1
    credentials:
      useDefaultAwsCredentialsChain: true
#    credentials:
#      access-key: dummy
#      secret-key: dummy
#    end-point:
#      uri: http://localhost:4566
#    queue:
#      uri: http://localhost:4566
#      name: sample-queue